export const mathsQuiz = [
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "What is the Roman numeral for 500?",
    correct_answer: "D",
    incorrect_answers: ["L", "C", "X"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question:
      "Which of these numbers is closest to the total number of possible states for an army standard Enigma Machine?",
    correct_answer: "1.58 x 10^20",
    incorrect_answers: ["1.58 x 10^22", "1.58 x  10^18", "1.58 x 10^24"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "What&#039;s the square root of 49?",
    correct_answer: "7",
    incorrect_answers: ["4", "12", "9"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "What shape does sin(x) or cos(x) make on a graph?",
    correct_answer: "Waves",
    incorrect_answers: ["A Parabola", "A Straight Line", "Zig-Zags"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question: "What is the fourth digit of &pi;?",
    correct_answer: "1",
    incorrect_answers: ["2", "3", "4"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "What is the derivative of sin(x)",
    correct_answer: "cos(x)",
    incorrect_answers: ["csc(x)", "-cos(x)", "-sin(x)"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question:
      "Which of the following famous mathematicians died in a duel at the age of 20?",
    correct_answer: "Galois",
    incorrect_answers: ["Abel", "Euler", "Gauss"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question:
      "The metric prefix &quot;atto-&quot; makes a measurement how much smaller than the base unit?",
    correct_answer: "One Quintillionth",
    incorrect_answers: [
      "One Billionth",
      "One Quadrillionth",
      "One Septillionth",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question: "What is the derivative of Acceleration with respect to time?",
    correct_answer: "Jerk",
    incorrect_answers: ["Shift", "Bump", "Slide"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question:
      "What is the area of a circle with a diameter of 20 inches if &pi;= 3.1415?",
    correct_answer: "314.15 Inches",
    incorrect_answers: ["380.1215 Inches", "3141.5 Inches", "1256.6 Inches"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "What Greek letter is used to signify summation?",
    correct_answer: "Sigma",
    incorrect_answers: ["Delta", "Alpha", "Omega"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "What type of function is x&sup2;+2x+1?",
    correct_answer: "Quadratic",
    incorrect_answers: ["Rational", "Linear", "Exponential"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question: "How many zeptometres are inside one femtometre?",
    correct_answer: "1,000,000",
    incorrect_answers: ["10", "1,000,000,000", "1000"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "What is the correct order of operations for solving equations?",
    correct_answer:
      "Parentheses, Exponents, Multiplication, Division, Addition, Subtraction",
    incorrect_answers: [
      "Addition, Multiplication, Division, Subtraction, Addition, Parentheses",
      "Parentheses, Exponents, Addition, Substraction, Multiplication, Division",
      "The order in which the operations are written.",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "How many books are in Euclid&#039;s Elements of Geometry?",
    correct_answer: "13",
    incorrect_answers: ["8", "10", "17"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question:
      "Which greek mathematician ran through the streets of Syracuse naked while shouting &quot;Eureka&quot; after discovering the principle of displacement?",
    correct_answer: "Archimedes",
    incorrect_answers: ["Euclid", "Homer", "Eratosthenes"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question:
      "What is the alphanumeric representation of the imaginary number?",
    correct_answer: "i",
    incorrect_answers: ["e", "n", "x"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "What are the first 6 digits of the number &quot;Pi&quot;?",
    correct_answer: "3.14159",
    incorrect_answers: ["3.14169", "3.12423", "3.25812"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question: "How many Millibars (mbar) to 1 Inch of Mercury (inHg)",
    correct_answer: "33.9",
    incorrect_answers: ["30.0", "27.4", "10.6"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question:
      "What is the plane curve proposed by Descartes to challenge Fermat&#039;s extremum-finding techniques called?",
    correct_answer: "Folium of Descartes",
    incorrect_answers: [
      "Elliptic Paraboloid of Descartes",
      "Cartesian Coordinates",
      "Descarte&#039;s Helicoid",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "What is the first Mersenne prime exponent over 1000?",
    correct_answer: "1279",
    incorrect_answers: ["2203", "1009", "1069"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question: "Integration is the reverse of what mathematical operation?",
    correct_answer: "Derivation",
    incorrect_answers: ["Division", "Standard Deviation", "Multiplication"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "In the hexadecimal system, what number comes after 9?",
    correct_answer: "The Letter A",
    incorrect_answers: ["10", "The Number 0", "16"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question:
      "The notion of a &quot;set that contains all sets which do not contain themselves&quot; is a paradoxical idea attributed to which English philosopher?",
    correct_answer: "Bertrand Russel",
    incorrect_answers: [
      "Francis Bacon",
      "John Locke",
      "Alfred North Whitehead",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question:
      "What is the smallest number that can be expressed as the sum of two positive cubes in two different ways?",
    correct_answer: "1729",
    incorrect_answers: ["91", "561", "4104"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "How many sides does a trapezium have?",
    correct_answer: "4",
    incorrect_answers: ["3", "5", "6"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "How many sides does a heptagon have?",
    correct_answer: "7",
    incorrect_answers: ["8", "6", "5"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "How many zeros are there in a googol?",
    correct_answer: "100",
    incorrect_answers: ["10", "1,000", "1,000,000"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "Which mathematician refused the Fields Medal?",
    correct_answer: "Grigori Perelman",
    incorrect_answers: ["Andrew Wiles", "Terence Tao", "Edward Witten"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "In Roman Numerals, what does XL equate to?",
    correct_answer: "40",
    incorrect_answers: ["60", "15", "90"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question: "What is the approximate value of mathematical constant e?",
    correct_answer: "2.72",
    incorrect_answers: ["3.14", "1.62", "1.41"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "At what temperature does temp in &deg;C equal temp in &deg;F?",
    correct_answer: "-40",
    incorrect_answers: ["+40", "0", "+100"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question: "The decimal number 31 in hexadecimal would be what?",
    correct_answer: "1F",
    incorrect_answers: ["3D", "2E", "1B"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question:
      "In the complex plane, multiplying a given function by i rotates it anti-clockwise by how many degrees?",
    correct_answer: "90",
    incorrect_answers: ["180", "270", "0"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "What is the equation for the area of a sphere?",
    correct_answer: "(4/3)&pi;r^3",
    incorrect_answers: ["4&pi;r^2", "(1/3)&pi;hr^2", "&pi;r^4"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question:
      "The French mathematician &Eacute;variste Galois is primarily known for his work in which?",
    correct_answer: "Galois Theory",
    incorrect_answers: [
      "Galois&#039; Continued Fractions",
      "Galois&#039; Method for PDE&#039;s ",
      "Abelian Integration",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Mathematics",
    question:
      "Which of the following mathematicians made major contributions to game theory?",
    correct_answer: "John Von Neumann",
    incorrect_answers: [
      "Carl Friedrich Gauss",
      "Leonhard Euler",
      "Stefan Banach",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "Which of the following dice is not a platonic solid?",
    correct_answer: "10-sided die",
    incorrect_answers: ["12-sided die", "20-sided die", "8-sided die"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Mathematics",
    question: "What prime number comes next after 19?",
    correct_answer: "23",
    incorrect_answers: ["25", "21", "27"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Mathematics",
    question: "What numbers are in the 5th row of Pascal&#039;s Triangle?",
    correct_answer: "1 4 6 4 1",
    incorrect_answers: ["1 3 3 1", "1 5 10 10 5 1", "1 6 15 20 15 6 1"],
  },
];
