export const scienceQuiz = [
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question:
      "This element, when overcome with extreme heat and pressure, creates diamonds.",
    correct_answer: "Carbon",
    incorrect_answers: ["Nitrogen", "Oxygen", "Hydrogen"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "Which of these stars is the largest?",
    correct_answer: "UY Scuti",
    incorrect_answers: ["VY Canis Majoris", "Betelgeuse", "RW Cephei"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question:
      "Which of the following blood vessels carries deoxygenated blood?",
    correct_answer: "Pulmonary Artery",
    incorrect_answers: ["Pulmonary Vein", "Aorta", "Coronary Artery"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "What is radiation measured in?",
    correct_answer: "Gray ",
    incorrect_answers: ["Watt", "Decibel", "Kelvin"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "Who developed the first successful polio vaccine in the 1950s?",
    correct_answer: "Jonas Salk",
    incorrect_answers: ["John F. Enders", "Thomas Weller", "Frederick Robbins"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question: "Folic acid is the synthetic form of which vitamin?",
    correct_answer: "Vitamin B",
    incorrect_answers: ["Vitamin A", "Vitamin C", "Vitamin D"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "How many bones are in the human body?",
    correct_answer: "206",
    incorrect_answers: ["203", "209", "200"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question:
      "Which of these two plates are best know for forming earthquakes and tsunami&#039;s? ",
    correct_answer: "Convergent Plate Boundaries/Oceanic Crust",
    incorrect_answers: [
      "Divergent Plate Boundaries/Convergent/Oceanic Crust",
      "Transform Plate Boundaries/Divergent Plate Boundaries",
      "Oceanic &amp; Continental Crust/Transform Plate Boundaries",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question: "Which of the following is a major muscle of the back?",
    correct_answer: "Trapezius",
    incorrect_answers: ["Trapezium", "Trapezoid", "Triquetrum"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "What is the scientific term for &#039;taste&#039;?",
    correct_answer: "Gustatory Perception",
    incorrect_answers: ["Olfaction", "Somatosensation", "Auditory Perception"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "Which of these Elements is a metalloid?",
    correct_answer: "Antimony",
    incorrect_answers: ["Tin", "Bromine", "Rubidium"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "What term is best associated with Sigmund Freud?",
    correct_answer: "Psychoanalysis",
    incorrect_answers: [
      "Cognitive-Behavioral Therapy",
      "Theory of Gravity",
      "Dialectical Behavior Therapy",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question:
      "Which desert is the only desert in the world where the &quot;Saguaro&quot; cactus grows indigenously?",
    correct_answer: "The Sonoran Desert",
    incorrect_answers: [
      "The Gobi Desert",
      "The Yuma Desert",
      "The Arabian Desert",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question:
      "What was the first organic compound to be synthesized from inorganic compounds?",
    correct_answer: "Urea",
    incorrect_answers: ["Propane", "Ethanol", "Formaldehyde"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question: "Which of the following is considered classical conditioning?",
    correct_answer: "Pavlov&#039;s dog experiments",
    incorrect_answers: [
      "Skinner box experiment",
      "Schr&ouml;dinger&#039;s cat experiment",
      "Harlow&rsquo;s monkey experiments",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question:
      "What is the molecular formula of the active component of chili peppers(Capsaicin)?",
    correct_answer: "C18H27NO3",
    incorrect_answers: ["C21H23NO3", "C6H4Cl2", "C13H25NO4"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question: "What causes the sound of a heartbeat?",
    correct_answer: "Closure of the heart valves",
    incorrect_answers: [
      "Contraction of the heart chambers",
      "Blood exiting the heart",
      "Relaxation of the heart chambers",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question:
      "Alzheimer&#039;s disease primarily affects which part of the human body?",
    correct_answer: "Brain",
    incorrect_answers: ["Lungs", "Skin", "Heart"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question:
      "Which of the following men does not have a chemical element named after him?",
    correct_answer: "Sir Isaac Newton",
    incorrect_answers: ["Albert Einstein", "Niels Bohr", "Enrico Fermi"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "What is the half-life of Uranium-235?",
    correct_answer: "703,800,000 years",
    incorrect_answers: [
      "4,300,400,000 years",
      "1,260,900,000 years",
      "Uranium-235 is a stable isotope",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question:
      "Along with Oxygen, which element is primarily responsible for the sky appearing blue?",
    correct_answer: "Nitrogen",
    incorrect_answers: ["Helium", "Carbon", "Hydrogen"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question:
      "All of the following human genetic haplogroup names are shared between Y-chromosome and mitochondrial DNA haplogroups EXCEPT:",
    correct_answer: "Haplogroup U",
    incorrect_answers: ["Haplogroup L", "Haplogroup T", "Haplogroup J"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "Who is the chemical element Curium named after?",
    correct_answer: "Marie &amp; Pierre Curie",
    incorrect_answers: [
      "The Curiosity Rover",
      "Curious George",
      "Stephen Curry",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "Stars consist mainly of hydrogen and which other gas?",
    correct_answer: "Helium",
    incorrect_answers: ["Oxygen", "Argon", "Nitrogen"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question: "What is the same in Celsius and Fahrenheit?",
    correct_answer: "-40",
    incorrect_answers: ["32", "-39", "-42"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "What is the Linnean name of the domestic apple tree?",
    correct_answer: "Malus pumila",
    incorrect_answers: [
      "Malus americana",
      "Pomus domestica",
      "Appelus delectica",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "What is the thin, outermost layer of the Earth?",
    correct_answer: "Crust",
    incorrect_answers: ["Exosphere", "Mantle", "Outer Core"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question: "What is isobutylphenylpropanoic acid more commonly known as?",
    correct_answer: "Ibuprofen",
    incorrect_answers: ["Morphine", "Ketamine", "Aspirin"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "The asteroid belt is located between which two planets?",
    correct_answer: "Mars and Jupiter",
    incorrect_answers: [
      "Jupiter and Saturn",
      "Mercury and Venus",
      "Earth and Mars",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question: "Which scientific unit is named after an Italian nobleman?",
    correct_answer: "Volt",
    incorrect_answers: ["Pascal", "Ohm", "Hertz"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "What is the chemical formula for ammonia?",
    correct_answer: "NH3",
    incorrect_answers: ["CO2", "NO3", "CH4"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question:
      "The humerus, paired radius, and ulna come together to form what joint?",
    correct_answer: "Elbow",
    incorrect_answers: ["Knee", "Sholder", "Ankle"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "Which planet in the Solar System is the closest to the Sun?",
    correct_answer: "Mercury",
    incorrect_answers: ["Earth", "Mars", "Venus"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "How many planets make up our Solar System?",
    correct_answer: "8",
    incorrect_answers: ["7", "9", "6"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science &amp; Nature",
    question:
      "A comet&#039;s gaseous envelope (which creates the tail) is called what?",
    correct_answer: "The coma",
    incorrect_answers: ["The wake", "The backwash", "The ablative"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "What did Gregory Mendel use to test genetic crossovers?",
    correct_answer: "Peas",
    incorrect_answers: ["Cats", "Flowers", "Parrots"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question:
      "What part of the brain takes its name from the Greek for seahorse?",
    correct_answer: "Hippocampus",
    incorrect_answers: ["Cerebellum", "Thalamus", "Amygdala"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question: "The Sun consists of mostly which two elements?",
    correct_answer: "Hydrogen &amp; Helium",
    incorrect_answers: [
      "Hydrogen &amp; Nitrogen",
      "Carbon &amp; Nitrogen",
      "Carbon &amp; Helium",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science &amp; Nature",
    question: "Which is the longest bone in the human body? ",
    correct_answer: "Femur",
    incorrect_answers: ["Scapula", "Fibula", "Ulna"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science &amp; Nature",
    question:
      "All the following metal elements are liquids at or near room temperature EXCEPT:",
    correct_answer: "Beryllium",
    incorrect_answers: ["Gallium", "Caesium", "Mercury"],
  },
];
