export const techQuiz = [
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question:
      "Moore&#039;s law originally stated that the number of transistors on a microprocessor chip would double every...",
    correct_answer: "Year",
    incorrect_answers: ["Four Years", "Two Years", "Eight Years"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question: "Which operating system was released first?",
    correct_answer: "Mac OS",
    incorrect_answers: ["Windows", "Linux", "OS/2"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question: "This mobile OS held the largest market share in 2012.",
    correct_answer: "iOS",
    incorrect_answers: ["Android", "BlackBerry", "Symbian"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question: "How many cores does the Intel i7-6950X have?",
    correct_answer: "10",
    incorrect_answers: ["12", "8", "4"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question: "Which of these people was NOT a founder of Apple Inc?",
    correct_answer: "Jonathan Ive",
    incorrect_answers: ["Steve Jobs", "Ronald Wayne", "Steve Wozniak"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question:
      "How many bits make up the significand portion of a single precision floating point number?",
    correct_answer: "23",
    incorrect_answers: ["8", "53", "15"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question: "Which of these programming languages is a low-level language?",
    correct_answer: "Assembly",
    incorrect_answers: ["Python", "C#", "Pascal"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Computers",
    question:
      "Which of these names was an actual codename for a cancelled Microsoft project?",
    correct_answer: "Neptune",
    incorrect_answers: ["Enceladus", "Pollux", "Saturn"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question:
      "What does the &#039;S&#039; in the RSA encryption algorithm stand for?",
    correct_answer: "Shamir",
    incorrect_answers: ["Secure", "Schottky", "Stable"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question:
      "In HTML, which non-standard tag used to be be used to make elements scroll across the viewport?",
    correct_answer: "&lt;marquee&gt;&lt;/marquee&gt;",
    incorrect_answers: [
      "&lt;scroll&gt;&lt;/scroll&gt;",
      "&lt;move&gt;&lt;/move&gt;",
      "&lt;slide&gt;&lt;/slide&gt;",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "The numbering system with a radix of 16 is more commonly referred to as ",
    correct_answer: "Hexidecimal",
    incorrect_answers: ["Binary", "Duodecimal", "Octal"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Computers",
    question: "Which kind of algorithm is Ron Rivest not famous for creating?",
    correct_answer: "Secret sharing scheme",
    incorrect_answers: [
      "Hashing algorithm",
      "Asymmetric encryption",
      "Stream cipher",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question: "In computing terms, typically what does CLI stand for?",
    correct_answer: "Command Line Interface",
    incorrect_answers: [
      "Common Language Input",
      "Control Line Interface",
      "Common Language Interface",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "The series of the Intel HD graphics generation succeeding that of the 5000 and 6000 series (Broadwell) is called:",
    correct_answer: "HD Graphics 500",
    incorrect_answers: [
      "HD Graphics 700 ",
      "HD Graphics 600",
      "HD Graphics 7000",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "Which computer hardware device provides an interface for all other connected devices to communicate?",
    correct_answer: "Motherboard",
    incorrect_answers: [
      "Central Processing Unit",
      "Hard Disk Drive",
      "Random Access Memory",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Computers",
    question:
      "According to the International System of Units, how many bytes are in a kilobyte of RAM?",
    correct_answer: "1000",
    incorrect_answers: ["512", "1024", "500"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Computers",
    question:
      "Which of the following is the oldest of these computers by release date?",
    correct_answer: "TRS-80",
    incorrect_answers: ["Commodore 64", "ZX Spectrum", "Apple 3"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Computers",
    question: "What port does HTTP run on?",
    correct_answer: "80",
    incorrect_answers: ["53", "443", "23"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question:
      "Which programming language was developed by Sun Microsystems in 1995?",
    correct_answer: "Java",
    incorrect_answers: ["Python", "Solaris OS", "C++"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Computers",
    question: "What is the main CPU is the Sega Mega Drive / Sega Genesis?",
    correct_answer: "Motorola 68000",
    incorrect_answers: ["Zilog Z80", "Yamaha YM2612", "Intel 8088"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Gadgets",
    question: "Which company developed the Hololens?",
    correct_answer: "Microsoft",
    incorrect_answers: ["HTC", "Oculus", "Tobii"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question: "What round is a classic AK-47 chambered in?",
    correct_answer: "7.62x39mm",
    incorrect_answers: ["7.62x51mm", "5.56x45mm", "5.45x39mm"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question: "When was the DVD invented?",
    correct_answer: "1995",
    incorrect_answers: ["2000", "1990", "1980"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question: "What does GPS stand for?",
    correct_answer: "Global Positioning System",
    incorrect_answers: [
      "Global Personal System",
      "General Positioning System",
      "General Personal Satellite",
    ],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Gadgets",
    question: "Which of the following is used to measure blood pressure?",
    correct_answer: "Sphygmomanometer",
    incorrect_answers: ["Barometer", "Ruler", "Haemoerythrometer"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Gadgets",
    question:
      "Who patented a steam engine that produced continuous rotary motion?",
    correct_answer: "James Watt",
    incorrect_answers: ["Nikola Tesla", "Albert Einstein", "Alessandro Volta"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Gadgets",
    question:
      "Which company designed the &quot;Betamax&quot; video cassette format?",
    correct_answer: "Sony",
    incorrect_answers: ["Panasonic", "LG", "Fujitsu"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question:
      "The term &quot;battery&quot; to describe an electrical storage device was coined by?",
    correct_answer: "Benjamin Franklin",
    incorrect_answers: ["Nikola Tesla", "Luigi Galvani", " Alessandro Volta"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question: "Which of the following is not a type of computer mouse?",
    correct_answer: "Smoothie mouse",
    incorrect_answers: ["Drum mouse", "Trackball mouse", "Optical mouse"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Gadgets",
    question:
      "Which of the following cellular device companies is NOT headquartered in Asia?",
    correct_answer: "Nokia",
    incorrect_answers: ["LG Electronics", "Samsung", "HTC"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question: "Which gaming console is developed by Sony?",
    correct_answer: "PlayStation",
    incorrect_answers: ["Xbox", "Atari", "Nintendo Switch"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Gadgets",
    question:
      "Out of all of the NASA Space Shuttles, which 2 have been destroyed in disasters?",
    correct_answer: "Challenger and Columbia",
    incorrect_answers: [
      "Enterprise and Atlantis",
      "Discovery and Endeavour",
      "None of the Above",
    ],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question: "When was the Tamagotchi digital pet released?",
    correct_answer: "1996",
    incorrect_answers: ["1989", "1992", "1990"],
  },
  {
    type: "multiple",
    difficulty: "hard",
    category: "Science: Gadgets",
    question: "Which round does a WW2 M1 Garand fire?",
    correct_answer: ".30-06",
    incorrect_answers: [".308", "7.62", "7.62x51mm"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question: "What does SSD stand for in the context of computer storage?",
    correct_answer: " Solid State Drive",
    incorrect_answers: [
      "Software Storage Device",
      "Super Speed Data",
      "Secure System Disk",
    ],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Gadgets",
    question:
      "In what year was the Oculus Rift revealed to the public through a Kickstarter campaign?",
    correct_answer: "2012",
    incorrect_answers: ["2010", "2011", "2013"],
  },
  {
    type: "multiple",
    difficulty: "medium",
    category: "Science: Gadgets",
    question:
      "What are the base station trackers used for the HTC Vive called?",
    correct_answer: "Lighthouse",
    incorrect_answers: ["Motion", "Constellation ", "Trackers"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question:
      "Which buzzword did Apple Inc. use to describe their removal of the headphone jack?",
    correct_answer: "Courage",
    incorrect_answers: ["Innovation", "Revolution", "Bravery"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question: "Which virtual assistant is developed by Amazon?",
    correct_answer: "Alexa",
    incorrect_answers: ["Google Assistant", "Siri", "Cortana"],
  },
  {
    type: "multiple",
    difficulty: "easy",
    category: "Science: Gadgets",
    question:
      "What is the name of a simple machine that is made up of a stiff arm that can move freely around a fixed point?",
    correct_answer: "Lever",
    incorrect_answers: ["Wedge", "Screw", "Pulley"],
  },
];
